// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQKjz2WHZqql-uYsS6_iSg4zCOO6YFi7o',
    appId: '1:1004698611646:android:da37068a095166459153ef',
    messagingSenderId: '1004698611646',
    projectId: 'helpme-bf036',
    databaseURL: 'https://helpme-bf036-default-rtdb.firebaseio.com',
    storageBucket: 'helpme-bf036.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp1yee0FXPv-G1ddxuAVR_FFoF0tL1geo',
    appId: '1:1004698611646:ios:9a9337dd1a81c00b9153ef',
    messagingSenderId: '1004698611646',
    projectId: 'helpme-bf036',
    databaseURL: 'https://helpme-bf036-default-rtdb.firebaseio.com',
    storageBucket: 'helpme-bf036.appspot.com',
    androidClientId: '1004698611646-1f8bmeqk3bu6icv194qp01mp4qo6v0da.apps.googleusercontent.com',
    iosBundleId: 'com.example.alarmApp',
  );
}
